# Generated by Django 5.0 on 2023-12-22 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_person_age_person_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="user_recommended",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.person",
            ),
        ),
    ]
