# Generated by Django 5.0 on 2023-12-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_person_about"),
    ]

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.ManyToManyField(to="core.event")),
                ("person", models.ManyToManyField(to="core.person")),
            ],
        ),
    ]
