# Generated by Django 5.0 on 2023-12-23 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_registration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registration",
            name="event",
        ),
        migrations.RemoveField(
            model_name="registration",
            name="person",
        ),
        migrations.AddField(
            model_name="registration",
            name="event",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="core.event"
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="person",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="core.person"
            ),
        ),
    ]
