# Generated by Django 5.0 on 2023-12-24 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_person_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="event",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.event",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="person",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.person",
            ),
        ),
    ]
